name: Update kakoune-overlay

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  flake-inputs:
    name: Update flake inputs
    runs-on: ubuntu-latest
    if: github.repository_owner == 'biocini'
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Add kakoune-overlay cache
        uses: cachix/cachix-action@v17
        with:
          name: kakoune-overlay
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update flake inputs
        run: |
          nix flake update
          git commit -m "Updated flake inputs" flake.lock || true

      - name: Push updated lock
        run: |
          git pull --rebase --autostash
          git push

  refresh-overlay:
    name: Refresh sources
    needs: flake-inputs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["core", "plugins"]
    if: github.repository_owner == 'biocini'
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Add kakoune-overlay cache
        uses: cachix/cachix-action@v17
        with:
          name: kakoune-overlay
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update sources
        run: |
          export GIT_PAGER=
          ./update ${{ matrix.repo }}

      - name: Push updated sources
        run: |
          git pull --rebase --autostash
          git push

  discover-new-plugins:
    name: Discover and propose new plugins
    needs: refresh-overlay
    runs-on: ubuntu-latest
    if: github.repository_owner == 'biocini'
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Dispatch new-plugin-pr workflow
        run: |
          gh workflow run new-plugin-pr.yml \
            --repo "${{ github.repository }}"
